### ISSUE TITLE
报错：dcqq转发服务器消息报错

### ISSUE THREAD

**Issue by LeoWrDeom** [Autuamn/nonebot-plugin-dcqq-relay#3]
discord to QQ，服务器消息无法转发，人发的消息是正常的
如图
![image](https://github.com/user-attachments/assets/18a59e88-12d8-4c49-b3f9-26f62f51504d)
![image](https://github.com/user-attachments/assets/1b82d3c5-9271-41ab-ba25-ec20f547cc95)
![image](https://github.com/user-attachments/assets/08a6c22e-0a45-46f5-9b01-5e3bc743759c)

```
08-09 22:50:22 [DEBUG] nonebot_plugin_dcqq_relay | into create_message()
08-09 22:50:22 [DEBUG] nonebot_plugin_dcqq_relay | into create_dc_to_qq()
08-09 22:50:22 [INFO] nonebot | Matcher(type='', module=nonebot_plugin_dcqq_relay, lineno=46) running complete
08-09 22:50:22 [ERROR] nonebot | Running Matcher(type='', module=nonebot_plugin_dcqq_relay, lineno=46) failed.
Traceback (most recent call last):
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 147, in execute
    self._adapt_connection._handle_exception(error)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 298, in _handle_exception
    raise error
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 129, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "FETCH": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\DiscordBot\lhcbot\bot.py", line 48, in <module>
    nonebot.run(app="__mp_main__:app")
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "G:\DiscordBot\Discordvenv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot_plugin_dcqq_relay\__init__.py", line 94, in create_message
    await create_dc_to_qq(bot, event, qq_bot, with_webhook_links)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot_plugin_dcqq_relay\dc_to_qq.py", line 164, in create_dc_to_qq    reply_id := await session.scalar(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 517, in scalar
    return await greenlet_spawn(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\orm\session.py", line 2399, in scalar
    return self._execute_internal(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\orm\session.py", line 2236, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\orm\context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 147, in execute
    self._adapt_connection._handle_exception(error)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 298, in _handle_exception
    raise error
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 129, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "FETCH": syntax error
[SQL: SELECT nonebot_plugin_dcqq_relay_msgid.qqid
FROM nonebot_plugin_dcqq_relay_msgid
WHERE nonebot_plugin_dcqq_relay_msgid.dcid = ?
 FETCH FIRST ? ROWS ONLY]
[parameters: (1271479356316713040, 1)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
08-09 22:50:22 [DEBUG] nonebot | Checking for matchers completed

```

**Comment by Autuamn** [comment]
请试试最新的开发版

**Comment by LeoWrDeom** [comment]
我试了最新的开发版，好像依然报错
```
08-12 10:16:05 [DEBUG] nonebot_plugin_dcqq_relay | into check_messages()
08-12 10:16:05 [INFO] nonebot | Event will be handled by Matcher(type='', module=nonebot_plugin_dcqq_relay, lineno=46)
08-12 10:16:05 [DEBUG] nonebot | Running Matcher(type='', module=nonebot_plugin_dcqq_relay, lineno=46)
08-12 10:16:05 [DEBUG] nonebot | Running handler Dependent(call=create_message)
08-12 10:16:05 [DEBUG] nonebot | Checking for matchers completed
08-12 10:16:05 [DEBUG] nonebot_plugin_dcqq_relay | into create_message()
08-12 10:16:05 [DEBUG] nonebot_plugin_dcqq_relay | into create_dc_to_qq()
08-12 10:16:05 [INFO] nonebot | Matcher(type='', module=nonebot_plugin_dcqq_relay, lineno=46) running complete
08-12 10:16:05 [ERROR] nonebot | Running Matcher(type='', module=nonebot_plugin_dcqq_relay, lineno=46) failed.
Traceback (most recent call last):
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 147, in execute
    self._adapt_connection._handle_exception(error)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 298, in _handle_exception
    raise error
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 129, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "FETCH": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\DiscordBot\lhcbot\bot.py", line 48, in <module>
    nonebot.run(app="__mp_main__:app")
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "G:\DiscordBot\Discordvenv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot_plugin_dcqq_relay\__init__.py", line 94, in create_message
    await create_dc_to_qq(bot, event, qq_bot, with_webhook_links)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\nonebot_plugin_dcqq_relay\dc_to_qq.py", line 164, in create_dc_to_qq
    reply_id := await session.scalar(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 517, in scalar
    return await greenlet_spawn(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\orm\session.py", line 2399, in scalar
    return self._execute_internal(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\orm\session.py", line 2236, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\orm\context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 147, in execute
    self._adapt_connection._handle_exception(error)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 298, in _handle_exception
    raise error
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 129, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "G:\DiscordBot\Discordvenv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "G:\DiscordBot\Discordvenv\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "FETCH": syntax error
[SQL: SELECT nonebot_plugin_dcqq_relay_msgid.qqid
FROM nonebot_plugin_dcqq_relay_msgid
WHERE nonebot_plugin_dcqq_relay_msgid.dcid = ?
 FETCH FIRST ? ROWS ONLY]
[parameters: (1272377785179963553, 1)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
08-12 10:16:05 [DEBUG] nonebot | Checking for matchers completed
```

**Comment by LeoWrDeom** [comment]
可以了，谢谢您！
